"""
Pick N random species per Flora de Costa Rica volume from the GBIF summary.

Source: outputs/gbif_species_summary.csv  (generated by summarize_gbif_dump.py)
Output: outputs/picked_species.csv

Volume definitions (Manual de Plantas de Costa Rica, family ranges):
  Vol II  — Gimnospermas + Monocotiledóneas (Agavaceae–Musaceae)
  Vol III — Monocotiledóneas (Orchidaceae–Zingiberaceae)
  Vol VI  — Dicotiledóneas (Haloragaceae–Phytolaccaceae)
  Vol VIII— Dicotiledóneas (Sabiaceae–Zygophyllaceae)

Usage:
    python utils/pick_species_by_volume.py [--n 25] [--min-occ 150] [--seed 42]
"""

import argparse
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import OUTPUT_BASE_DIR

INPUT_CSV  = os.path.join(OUTPUT_BASE_DIR, "gbif_species_summary.csv")
OUTPUT_CSV = os.path.join(OUTPUT_BASE_DIR, "picked_species.csv")

# ---------------------------------------------------------------------------
# Volume definitions
# Each entry: (label, filter_function)
# ---------------------------------------------------------------------------
VOLUMES = [
    {
        "volume": "Vol. II",
        "title": "Gimnospermas y Monocotiledóneas (Agavaceae–Musaceae)",
        "filter": lambda df: df[
            # Gymnosperms (any family)
            df["class"].isin(["Pinopsida", "Cycadopsida", "Gnetopsida"]) |
            # Monocots, families Agavaceae → Musaceae
            (
                (df["class"] == "Liliopsida") &
                (df["family"] >= "Agavaceae") &
                (df["family"] <= "Musaceae")
            )
        ],
    },
    {
        "volume": "Vol. III",
        "title": "Monocotiledóneas (Orchidaceae–Zingiberaceae)",
        "filter": lambda df: df[
            (df["class"] == "Liliopsida") &
            (df["family"] >= "Orchidaceae") &
            (df["family"] <= "Zingiberaceae")
        ],
    },
    {
        "volume": "Vol. VI",
        "title": "Dicotiledóneas (Haloragaceae–Phytolaccaceae)",
        "filter": lambda df: df[
            (df["class"] == "Magnoliopsida") &
            (df["family"] >= "Haloragaceae") &
            (df["family"] <= "Phytolaccaceae")
        ],
    },
    {
        "volume": "Vol. VIII",
        "title": "Dicotiledóneas (Sabiaceae–Zygophyllaceae)",
        "filter": lambda df: df[
            (df["class"] == "Magnoliopsida") &
            (df["family"] >= "Sabiaceae") &
            (df["family"] <= "Zygophyllaceae")
        ],
    },
]


def is_binomial(name: str) -> bool:
    """Return True only for proper binomial names (Genus epithet [author...])."""
    parts = str(name).split()
    if len(parts) < 2:
        return False
    # Reject entries that are family/genus-only (single capitalised word)
    # or end with taxonomic author abbreviations like "L.", "Ruiz & Pav."
    # Simple heuristic: second token must start with a lowercase letter
    return parts[1][0].islower()


def pick(df: pd.DataFrame, n: int, min_occ: int, seed: int, vol: dict) -> pd.DataFrame:
    pool = vol["filter"](df)
    pool = pool[pool["occurrences"] >= min_occ]
    pool = pool[pool["species"].apply(is_binomial)]

    available = len(pool)
    chosen_n  = min(n, available)

    if available == 0:
        print(f"  [!] {vol['volume']} — no eligible species found (min_occ={min_occ})")
        return pd.DataFrame()

    if available < n:
        print(f"  [!] {vol['volume']} — only {available} eligible species; picking all {available}")

    sample = pool.sample(n=chosen_n, random_state=seed)
    sample = sample.sort_values("occurrences", ascending=False).copy()
    sample.insert(0, "volume",  vol["volume"])
    sample.insert(1, "volume_title", vol["title"])
    return sample


def main():
    parser = argparse.ArgumentParser(description="Pick random species per Flora de CR volume.")
    parser.add_argument("--input",   default=INPUT_CSV,  help="Path to gbif_species_summary.csv")
    parser.add_argument("--output",  default=OUTPUT_CSV, help="Path for picked_species.csv")
    parser.add_argument("--n",       type=int, default=25,  help="Species to pick per volume (default: 25)")
    parser.add_argument("--min-occ", type=int, default=150, help="Minimum occurrences (default: 150)")
    parser.add_argument("--seed",    type=int, default=42,  help="Random seed for reproducibility (default: 42)")
    args = parser.parse_args()

    print(f"Loading: {args.input}")
    df = pd.read_csv(args.input, dtype={"class": str, "family": str, "phylum": str, "order": str})

    frames = []
    for vol in VOLUMES:
        result = pick(df, args.n, args.min_occ, args.seed, vol)
        if not result.empty:
            frames.append(result)
            print(f"  {vol['volume']:10s} — picked {len(result):>2d} species  "
                  f"(pool had {len(vol['filter'](df).query('occurrences >= @args.min_occ')):>3d} eligible)")

    if not frames:
        print("No species selected. Check --min-occ threshold.")
        return

    out = pd.concat(frames, ignore_index=True)
    out.to_csv(args.output, index=False, encoding="utf-8")

    print(f"\nTotal species selected : {len(out)}")
    print(f"Output saved to        : {os.path.abspath(args.output)}")
    print()
    print(out[["volume", "species", "family", "class", "occurrences"]].to_string(index=False))


if __name__ == "__main__":
    main()
